$(document).ready(function(){
    $(".day1").click(function(){
        $("#day1").remove();
    });
    $(".day2").click(function(){
        $("#day2").remove();
    });
    $(".day3").click(function(){
        $("#day3").remove();
    });
    $(".day4").click(function(){
        $("#day4").remove();
    });
    $(".day5").click(function(){
        $("#day5").remove();
    });
    $(".day6").click(function(){
        $("#day6").remove();
    });
    $(".day7").click(function(){
        $("#day7").remove();
    });
    $(".day8").click(function(){
        $("#day8").remove();
    });
    $(".day9").click(function(){
        $("#day9").remove();
    });
    $(".day10").click(function(){
        $("#day10").remove();
    });
    $(".day11").click(function(){
        $("#day11").remove();
    });
    $(".day12").click(function(){
        $("#day12").remove();
    });
});